# Inteiros

## Algoritmos de Divisão

### 1.1 Teste de exemplos:

Nesta seção, testarei os seguintes exemplos:  
- $3 \mid 15$;  
- $6 \mid 15$;  
- $0 \mid 0$;  
- $1 \mid -1$.  




In [1]:
def div(b, a):
    if b == 0 and a == 0:
        print(b, '|', a)  # Por definição, 0 divide 0
    elif b == 0:
        print(b, '∤',a)  # 0 não divide nenhum número, exceto 0
    elif a % b == 0:
        print(b, '|', a)
    else:
        print(b, '∤',a)

test_cases = [(3, 15), (6, 15), (0, 0), (1, -1)]

for b, a in test_cases:
    div(b, a)

3 | 15
6 ∤ 15
0 | 0
1 | -1


**if — linha 2:** trata o caso especial \($0 \mid 0$).  
**elif — linha 4:** trata divisor zero (exceto o caso acima).


### 1.2 Teste das Propriedades

Nesta seção, testarei as seguintes propriedades:


$$i)\quad c \mid b \land b \mid a \Rightarrow c \mid a$$  

$$ii)\quad b \mid a \land b \mid a' \Rightarrow b \mid (a + a')$$   

$$ iii)\quad b \mid 0 \ \text{$\forall$ } b \in \mathbb{Z}\ $$   

$$iv)\quad 1 \mid a \ \text{$\forall$ } a \in \mathbb{Z}$$   

$$v)\quad 0 \mid a \iff a = 0$$  

In [2]:
#Verifica se b divide a (retorna True/False).
def divide(b, a):
     if b == 0:
        return a == 0  # 0 só divide 0
     return a % b == 0  # Caso geral

Função auxiliar para divisibilidade.

##### Propriedade (i) - Transitividade  
$ i)\quad c \mid b \land b \mid a \Rightarrow c \mid a  $  

In [3]:
exemplos_1 = [(2, 6, 12), (3, 9, 27), (7,14,84), (4, 8, 15)]

def transitividade():
    for c, b, a in exemplos_1:
        # Verifica se as premissas são verdadeiras (c|b E b|a)
        premissas_validas = divide(c, b) and divide(b, a)
        
        # Se as premissas forem válidas, verifica a conclusão (c|a)
        if premissas_validas:
            conclusao = divide(c, a)
            print(f"{c}|{b} e {b}|{a} ⇒ {c}|{a}? {conclusao} (Transitividade válida)")
        else:
            # Mostra qual premissa falhou
            if not divide(c, b):
                print(f"{c}∤{b} (Premissa c|b inválida) ⇒ Transitividade não aplicável")
            elif not divide(b, a):
                print(f"{b}∤{a} (Premissa b|a inválida) ⇒ Transitividade não aplicável")
transitividade()

2|6 e 6|12 ⇒ 2|12? True (Transitividade válida)
3|9 e 9|27 ⇒ 3|27? True (Transitividade válida)
7|14 e 14|84 ⇒ 7|84? True (Transitividade válida)
8∤15 (Premissa b|a inválida) ⇒ Transitividade não aplicável


##### Propriedade (ii) - Linearidade:
##### $ii) b \mid a \land b \mid a' \Rightarrow b \mid a+a'$ 

In [4]:
exemplos_2 = [(2,4,10), (3,9,30), (5,15,85), (9,36,49)]

def lineariedade():
    for c, b, a in exemplos_2:
        # Verifica se as premissas são verdadeiras (c|b E b|a)
        premissas_validas = divide(c, b) and divide(c, a)
        
        # Se as premissas forem válidas, verifica a conclusão (c|a)
        if premissas_validas:
            conclusao = divide(c, b+a)
            print(f"{c}|{b} e {c}|{a} ⇒ {c}|{b+a}? {conclusao} (Lineariedade válida)")
        else:
            # Mostra qual premissa falhou
            if not divide(c, b):
                print(f"{c}∤{b} (Premissa b|a inválida) ⇒ Lineariedade não aplicável")
            elif not divide(b, a):
                print(f"{c}∤{a} (Premissa b|a' inválida) ⇒ Lineariedade não aplicável")
lineariedade()

2|4 e 2|10 ⇒ 2|14? True (Lineariedade válida)
3|9 e 3|30 ⇒ 3|39? True (Lineariedade válida)
5|15 e 5|85 ⇒ 5|100? True (Lineariedade válida)
9∤49 (Premissa b|a' inválida) ⇒ Lineariedade não aplicável


##### Propriedade (iii) - Divisibilidade do Zero:  
##### $iii)\quad b \mid 0 \ \text{$\forall$ } b \in \mathbb{Z}\$

In [5]:
def divisibilidadeDoZero():
    for b in range(-2,3):
        if divide(b,0):
            conclusao = print(f"{b}|{0})? {divide(b,0)} (Divisibilidade do zero válida)")
        else:
            print("Não aplicável")
            
divisibilidadeDoZero()
        
        

-2|0)? True (Divisibilidade do zero válida)
-1|0)? True (Divisibilidade do zero válida)
0|0)? True (Divisibilidade do zero válida)
1|0)? True (Divisibilidade do zero válida)
2|0)? True (Divisibilidade do zero válida)


##### Divisibilidade por Um:  
  $iv)\quad 1 \mid a \ \text{$\forall$ } a \in \mathbb{Z}$


In [6]:
def divisibilidadePorUm():
    for a in range(-2,3):
        if divide(1,a):
            conclusao = print(f"{1}|{a} ? {divide(1,a)} (Divisibilidade por um válida)")
        else:
            print("Não aplicável")

divisibilidadePorUm()
            

1|-2 ? True (Divisibilidade por um válida)
1|-1 ? True (Divisibilidade por um válida)
1|0 ? True (Divisibilidade por um válida)
1|1 ? True (Divisibilidade por um válida)
1|2 ? True (Divisibilidade por um válida)


##### Propriedade (v) - Divisibilidade por Zero:  
  $v)\quad 0 \mid a \iff a = 0$

In [7]:
def divisibilidadePorZero():
    for a in range(-2,3):
        premissa_valida = a == 0

        if premissa_valida:
            conclusao = print(f"{0}|{a} ? {divide(a,a)} (Divisibilidade por Zero)")
        else:
            print(f"{0}|{a} ? Não aplicável, premissa a = 0 não satisfeita")

divisibilidadePorZero()
            

0|-2 ? Não aplicável, premissa a = 0 não satisfeita
0|-1 ? Não aplicável, premissa a = 0 não satisfeita
0|0 ? True (Divisibilidade por Zero)
0|1 ? Não aplicável, premissa a = 0 não satisfeita
0|2 ? Não aplicável, premissa a = 0 não satisfeita


### 1.3 A Lista de Divisores

Nesta seção, calcularei a lista de divisores de $48$, e para algum outro número $m < 200$ -> $m = 149.$

In [8]:
>>> D48 = [d for d in range (1,49) if 48%d == 0]
>>> D48

[1, 2, 3, 4, 6, 8, 12, 16, 24, 48]

In [9]:
>>> m = 149
>>> D149 = [ d for d in range (1,m+1) if m%d == 0]
>>> D149

[1, 149]

### 1.4 Calculando len() e sum() para D48 e D149:

Nesta seção, calcularei o numero de divisores de 48, 149, e a soma entre esses divisores.

Calculando os valores para 48:

In [10]:
>>> len(D48)

10

In [11]:
>>> sum(D48)

124

Calculando os valores para 149

In [12]:
>>> len(D149)

2

In [13]:
>>> sum(D149)

150

### 1.5 Encontrando todos os número perfeitos menores que 1000

Nesta seção, encontrarei todos os números perfeitos menores que 1000

Um número é perfeito se ele é igual à soma de seus divisores, excluindo ele mesmo. Então se $\sum_{d \mid n} d = 2n $ 
. Escreva um programa para encontrar todos os números perfeitos menores que 1000.

In [14]:
def numeroPerfeito():
    for i in range(1,1000):
        Di = [ d for d in range(1,i) if i%d==0]
        if sum(Di) == i: print("O número", i, "eh perfeito")
numeroPerfeito()

O número 6 eh perfeito
O número 28 eh perfeito
O número 496 eh perfeito


### 1.6 Algoritmo de Euclides

Nesta seção, modifcarei o programa dado para mostrar todas as etapas intermidiárias, verificarei exemplo e calcularei o MDC entre minha minha matrícula e meu número de telefone.

Função que mostra as etapas intermediárias do Algoritmo de Euclides

In [15]:
def gcd_euclid_iterative(a, b):
    # Calcula o MDC usando o algoritmo de Euclides (versão iterativa - mostrando as etapas intermediárias)
    print(f"r0 = {a}\nr1 = {b}\n----------------------------")
    i = 2
    (r0, r1) = (a, b)
    
    while b != 0:
        q = a // b  # Calcula o quociente antes de atualizar a e b
        print(f"{a} = {q}·{b} + {a%b}")
        (a, b) = (b, a % b)  # Atualiza os valores para o próximo passo
        print(f"r{i} = {b} |", end=' ')
        print(f"q{i-1} = {q}\n----------------------------")
        i += 1
    
    return print(f"GCD({r0}, {r1}) = r{i-2} = {a}")

Verificando o exemplo: $MDC(1057,315)$

In [16]:
def gcd_euclid_iterative(a, b):
    # Calcula o MDC usando o algoritmo de Euclides (versão iterativa - mostrando as etapas intermediárias)
    print(f"r0 = {a}\nr1 = {b}\n----------------------------")
    i = 2
    (r0, r1) = (a, b)
    
    while b != 0:
        q = a // b  # Calcula o quociente antes de atualizar a e b
        print(f"{a} = {q}·{b} + {a%b}")
        (a, b) = (b, a % b)  # Atualiza os valores para o próximo passo
        print(f"r{i} = {b} |", end=' ')
        print(f"q{i-1} = {q}\n----------------------------")
        i += 1
    
    return print(f"GCD({r0}, {r1}) = r{i-2} = {a}")

gcd_euclid_iterative(1057, 315)

r0 = 1057
r1 = 315
----------------------------
1057 = 3·315 + 112
r2 = 112 | q1 = 3
----------------------------
315 = 2·112 + 91
r3 = 91 | q2 = 2
----------------------------
112 = 1·91 + 21
r4 = 21 | q3 = 1
----------------------------
91 = 4·21 + 7
r5 = 7 | q4 = 4
----------------------------
21 = 3·7 + 0
r6 = 0 | q5 = 3
----------------------------
GCD(1057, 315) = r5 = 7


Calculando o MDC entre minha matrícula e meu número de telefone:

In [17]:
def gcd_euclid_iterative(a, b):
    # Calcula o MDC usando o algoritmo de Euclides (versão iterativa - mostrando as etapas intermediárias)
    print(f"r0 = {a}\nr1 = {b}\n-----------------------------------------------")
    i = 2
    (r0, r1) = (a, b)
    
    while b != 0:
        q = a // b  # Calcula o quociente antes de atualizar a e b
        print(f"{a} = {q}·{b} + {a%b}")
        (a, b) = (b, a % b)  # Atualiza os valores para o próximo passo
        print(f"r{i} = {b} |", end=' ')
        print(f"q{i-1} = {q}\n-----------------------------------------------")
        i += 1
    
    return print(f"GCD({r0}, {r1}) = r{i-2} = {a}")

gcd_euclid_iterative(2024106034, 31971466441)

r0 = 2024106034
r1 = 31971466441
-----------------------------------------------
2024106034 = 0·31971466441 + 2024106034
r2 = 2024106034 | q1 = 0
-----------------------------------------------
31971466441 = 15·2024106034 + 1609875931
r3 = 1609875931 | q2 = 15
-----------------------------------------------
2024106034 = 1·1609875931 + 414230103
r4 = 414230103 | q3 = 1
-----------------------------------------------
1609875931 = 3·414230103 + 367185622
r5 = 367185622 | q4 = 3
-----------------------------------------------
414230103 = 1·367185622 + 47044481
r6 = 47044481 | q5 = 1
-----------------------------------------------
367185622 = 7·47044481 + 37874255
r7 = 37874255 | q6 = 7
-----------------------------------------------
47044481 = 1·37874255 + 9170226
r8 = 9170226 | q7 = 1
-----------------------------------------------
37874255 = 4·9170226 + 1193351
r9 = 1193351 | q8 = 4
-----------------------------------------------
9170226 = 7·1193351 + 816769
r10 = 816769 | q9 = 7
-------

### 1.7 Algoritmo de Euclides e Números de Fibonacci

Nesta seção, irei executar o programa modificado em $a = 4181$ e $b = 2584$, dois número consecutivos da sequência de Fibonacci.
Irei relatar o que vejo e justificarei o motivo de este ser o pior caso para o Algoritmo de Euclides



In [18]:
def gcd_euclid_iterative(a, b):
    # Calcula o MDC usando o algoritmo de Euclides (versão iterativa - mostrando as etapas intermediárias)
    print(f"r0 = {a}\nr1 = {b}\n-----------------------------------------------")
    i = 2
    (r0, r1) = (a, b)
    
    while b != 0:
        q = a // b  # Calcula o quociente antes de atualizar a e b
        print(f"{a} = {q}·{b} + {a%b}")
        (a, b) = (b, a % b)  # Atualiza os valores para o próximo passo
        print(f"r{i} = {b} |", end=' ')
        print(f"q{i-1} = {q}\n-----------------------------------------------")
        i += 1
    
    return print(f"GCD({r0}, {r1}) = r{i-2} = {a}")

gcd_euclid_iterative(4181, 2584)

r0 = 4181
r1 = 2584
-----------------------------------------------
4181 = 1·2584 + 1597
r2 = 1597 | q1 = 1
-----------------------------------------------
2584 = 1·1597 + 987
r3 = 987 | q2 = 1
-----------------------------------------------
1597 = 1·987 + 610
r4 = 610 | q3 = 1
-----------------------------------------------
987 = 1·610 + 377
r5 = 377 | q4 = 1
-----------------------------------------------
610 = 1·377 + 233
r6 = 233 | q5 = 1
-----------------------------------------------
377 = 1·233 + 144
r7 = 144 | q6 = 1
-----------------------------------------------
233 = 1·144 + 89
r8 = 89 | q7 = 1
-----------------------------------------------
144 = 1·89 + 55
r9 = 55 | q8 = 1
-----------------------------------------------
89 = 1·55 + 34
r10 = 34 | q9 = 1
-----------------------------------------------
55 = 1·34 + 21
r11 = 21 | q10 = 1
-----------------------------------------------
34 = 1·21 + 13
r12 = 13 | q11 = 1
-----------------------------------------------
21 = 1·13 + 8

É perceptível que, em todos as etapas, o maior coeficiente presente é o número 1.

Este caso é o pior para o Algoritmo de Euclides, pois é necessária a realização de inúmeras divisões sucessivas pelos restos das etapas anteriores, para que no fim o MDC seja 1

# Números primos

### 2.1 Verificar se um número é primo

Nesta seção, implementarei uma função que verifica se um número é primo.

In [19]:
import math
def ehPrimo(n):
    for d in range(2,round(math.sqrt(n)+1)):
        if (n % d==0):
            print("Não eh primo, divisor encontrado:", d)
            return False
    print("Eh primo")
    return True

ehPrimo(65537)

Eh primo


True

### 2.2 Primo de Mersenne

Nesta seção, encontrarei na internet o maior número primo conhecido e indicarei se é um primo de $Mersene$.  
**Definição:** um primo de $Mersene$ é um primo da forma de $M_{k} = 2^{k} - 1$.

O maior número primo conhecido é o número $2^{136279841} - 1$.  
Percebe-se que este número segue a forma $2^{k} - 1$, portanto, é um primo de $Mersene$: $M_{136279841} = 2^{136279841} - 1$.


### 2.3 Representação binária de 257 e 65537

Nesta seção, implementarei um comando em python para encontrar a representação binária de 257 e 65537 (e qualquer outro numero inteiro).

Função para encontrar a representação binária de qualquer número Inteiro:

In [10]:
def representacaoBinaria(n):
    num=n
    numeros = []
    #print(n)
    while n!=1:
        resto = n%2
        n = n//2
        numeros.insert(0, resto)
        #print(resto, n) # Imprime as etapas intermediárias
    numeros.insert(0, n)
    print(f"O número {num} em binário é:", end="")
    print("".join(str(item) for item in numeros))

Encontrando a representação binária de 257 e 65537 usando o algoritmo acima:

In [9]:
representacaoBinaria(257)
representacaoBinaria(65537)

O número 257 em binário é:100000001
O número 65537 em binário é:10000000000000001


Encontrando a representação binária de 257 e 65537 usando a função bin do python

In [14]:
print(bin(257)[2:])
print(bin(65537)[2:])

100000001
10000000000000001


### 2.4 Estimando Primos de Tamanhos Criptográficos com o 'Teorema dos Números Primos'

Nesta seção, irei estimar a quantidade de números primos com tamanhos de 1024 bits, 1536 bits e 2048 bits (os tamanhos usados na criptografia)

$$Teorema\enspace dos \enspace Números \enspace Primos:$$
$$ \lim_{N \to \infty} \frac{\pi(N)}{N} \sim \frac{1}{\ln(N)} $$

In [1]:
import math

def eh_primo(n):
    for d in range(2,round(math.sqrt(n)+1)):
        if (n % d==0):
            return False
    return True

def pi(x):
    count = 0
    for i in range(2, x+1):
        if eh_primo(i):
            count +=1
    return count

def verificarTeorema(x):
    pi_x = pi(x)
    aprox = x / math.log(x) if x > 1 else 0
    print(f"π({x}) = {pi_x}")
    print(f"Aproximação pelo Teorema dos Números Primos: {aprox:.2f}")
    print(f"Razão π({x})/({x}) = {pi_x/x:.5f}")
    print(f"1/ln({x}) = {1/math.log(x):.5f}\n")

from decimal import Decimal, getcontext

getcontext().prec = 1000

def estimarPrimos(x):
    x_decimal = Decimal(x)
    aprox = x_decimal / x_decimal.ln() if x_decimal > 1 else 0
    print(f"Aproximação pelo Teorema dos Números Primos para x = {x_decimal:.2e}:\n≈ {aprox:.2e}\n")

valores = [2**1024, 2**1536, 2**2048]


for v in valores:
    estimarPrimos(v)


Aproximação pelo Teorema dos Números Primos para x = 1.80e+308:
≈ 2.53e+305

Aproximação pelo Teorema dos Números Primos para x = 2.41e+462:
≈ 2.26e+459

Aproximação pelo Teorema dos Números Primos para x = 3.23e+616:
≈ 2.28e+613



### 2.5 Testando o Teorema de Fermat

Nesta seção, testarei o Teorema de Fermat.



$$Teorema\enspace de\enspace Fermat:$$
<p style="text-align:center">Se $p$ é um número primo, então: </p>

$$a^{p-1} \equiv 1 \pmod{p} \space \forall \space a  \in [1, p-1] $$


<p style="text-align:center"><strong>Contra-positivo:</strong> $a^{n-1} \not\equiv 1 \pmod{n}$ para algum $a \in [1, n-1]$, então n é composto<p/>


In [3]:
import random

def fermat_primality_test(n, k=10):
    if n <= 3:
        return n == 2 or n == 3

    for _ in range(k):
        a = random.randint(2, n - 2)
        if pow(a, n - 1, n) != 1:
            return False  # composto
    return True  # provavelmente primo

numero = 6553 #int(input("Digite um número para testar: "))
if fermat_primality_test(numero):
    print(f"{numero} é provavelmente primo.")
else:
    print(f"{numero} é composto.")


6553 é provavelmente primo.


### 2.6 Construindo um Número Primo com Meu Nome

Nesta seção, criarei um número primo com meu nome.

Instruções:

1. **Crie um frase** com cerca de 45 letras contendo seu nome;

2. **Converta pra números** como segue: $A = 1,..., Z = 26,$ space $= 27$, etc. Concatenando os dígitos, você obterá um número com cerca de 90 dígitos;

3. **Complete com 10 dígitos aleatórios** para obter um número ímpar de 100 dígitos $n$ e teste se $n$ é primo. Caso contrário, altere os últimos 10 dígitos até que $n$ seja primo;

4. **Teste de primalidade**:  você pode usar `fermat_primality_test(n, k=10)`.

In [13]:
import random

def letra_para_numero(c):
    if c == ' ':
        return '27'
    else:
        return f"{ord(c.upper()) - ord('A') + 1:02d}"

def frase_para_numero(frase):
    return ''.join(letra_para_numero(c) for c in frase if c.isalpha() or c == ' ')

def gerar_numero_primo(frase):
    base_numero = frase_para_numero(frase)
    
    while True:
        sufixo = ''.join(random.choice('0123456789') for _ in range(9))
        #print(sufixo)
        ultimo_digito = random.choice('13579')
        numero_str = base_numero + sufixo + ultimo_digito
        numero = int(numero_str)
        
        if fermat_primality_test(numero):
            return numero

# FRASE EM UPERCASE
frase = "MARNEY MELO GOSTOU MUITO DE ESTUDAR OS NÚMEROS PRIMOS"
numero_primo = gerar_numero_primo(frase)

#print(f"Nome em números: {frase_para_numero(frase)}")
print(f"Número primo gerado: {numero_primo}")
print(f"Número de dígitos: {len(str(numero_primo))}")


Número primo gerado: 130118140525271305121527071519201521271321092015270405270519202104011827151927141541305181519271618091315198192233763
Número de dígitos: 117
